
---
spring:
  config.activate.on-profile: local
  # In 'Spring Tool Suite', set datasource as arguments in 'Boot Dashboard' view:
  # right clic on the app > open config > arguments tab > in 'Program arguments' set:
  datasource:
    url: jdbc:postgresql://localhost:5432/flightReview
    username: postgres
    password: a
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false


